version: "3"
services:
  pipeline-ui:
    build: "./pipeline-ui"
    container_name: "config_tester"
    ports:
      - "8080:8080"
    volumes:
      - "./logstash/logstash-config/pipeline:/usr/src/pipeline"
  logstash:
    build: "./logstash"
    container_name: "logstash"
    ports:
      - "9600:9600"
      - "5060:5060"
    volumes:
      - "./logstash/logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/logstash-config/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
      - "./logstash/logstash-config/pipeline:/usr/share/logstash/pipeline"
