name: Test build and linting

on: [pull_request]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        working-directory: ./pipeline-ui/backend
        run: npm install
      - name: Lint
        working-directory: ./pipeline-ui/backend
        run: npm run lint
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        working-directory: ./pipeline-ui/frontend
        run: npm install
      - name: Lint
        working-directory: ./pipeline-ui/frontend
        run: npm run lint
  integration-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: pipeline-ui/integration-tests
          wait-on: 'http://localhost:8080'
          start: npm start
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
